// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AreaChart: typeof import('./src/components/widget/area-chart.vue')['default']
    BarChart: typeof import('./src/components/widget/bar-chart.vue')['default']
    CreateViewDialog: typeof import('./src/components/createView-dialog/index.vue')['default']
    CustomSearch: typeof import('./src/components/widget/custom-search.vue')['default']
    CustomText: typeof import('./src/components/widget/custom-text.vue')['default']
    CustomVideo: typeof import('./src/components/widget/custom-video.vue')['default']
    CutomBtn: typeof import('./src/components/widget/cutom-btn.vue')['default']
    CutomInput: typeof import('./src/components/widget/cutom-input.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StyleSider: typeof import('./src/components/style-sider/index.vue')['default']
    ToolList: typeof import('./src/components/tool-list/index.vue')['default']
    WidgetList: typeof import('./src/components/widget-list/index.vue')['default']
  }
}
